[metadata]
name = "code"
description = "Browse ~/code directories and their git worktrees"
requirements = []

[source]
command = "ls -d ~/code/*"

# '{}' is placeholder for where the item from the list will be substituted in the command.
[preview]
command = "basename -- '{}'"

[keybindings]
# runs the [actions.open] action when you press enter on an item in the list.
enter = "actions:open"

[actions.open]
description = "Show worktrees in this directory"
command = "TV_CODE_DIR='{}' tv code-wt"
mode = "execute" # runs the command and exits tv